AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  mymacie

  SAM Template for mymacie
  
Globals:
  Function:
    Timeout: 3

Resources:
  MacieFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: macie/
      Handler: app.lambdaHandler
      Runtime: nodejs14.x
      Architectures:
        - x86_64
      Events:
        Macie:
          Type: Api 
          Properties:
            Path: /macie
            Method: get

Outputs:
  MacieApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub
  MacieFunction:
    Description: "Macie Lambda Function ARN"
    Value: !GetAtt MacieFunction.Arn
  MacieFunctionIamRole:
    Description: "Implicit IAM Role created for Macie function"
    Value: !GetAtt MacieFunctionRole.Arn
